### PR TITLE
Adjust pretty name of closures on PHP 8.4

### PR DESCRIPTION
**Pull request by staabm**
related to https://github.com/php/php-src/pull/13550

see analog symfony change: https://github.com/symfony/symfony/pull/54614

### CODE REVIEW

**Comment by mabar** [comment]
Thanks

**Comment by TimWolla** [comment]
FWIW: For PHP 8.4 you might want to consider just using the original Closure name as-is. My understanding is that this code attempts to do what PHP 8.4 now natively does and arguably does better.

**Comment by staabm** [comment]
This change would require raising the minimum php version requirement for this package

**Comment by TimWolla** [comment]
> This change would require raising the minimum php version requirement for this package

I just looked at your patch and the immediate context (i.e. no tests or so). Would a `PHP_VERSION_ID < 80400`-check not work?

**Comment by mabar** [comment]
This package does not support nor tests PHP 8.4 yet. I'll look at it again once I add official support, thanks

**Pull request merged**
